name: ledger_cardano_plus
description: A Ledger App Plugin for the Cardano blockchain
version: 0.1.6
homepage: https://github.com/vespr-wallet/ledger-cardano-plus
repository: https://github.com/vespr-wallet/ledger-cardano-plus
issue_tracker: https://github.com/vespr-wallet/ledger-cardano-plus/issues

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

  ledger_flutter_plus: ^1.0.9
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  bech32: ^0.2.2
  base_x: ^2.0.1

# dependency_overrides:
#   meta: 1.14.0

dev_dependencies:
  # integration_test:
  #   sdk: flutter
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  build_runner:

flutter:
